### ISSUE TITLE
Create endpoint for getting motd

### ISSUE THREAD

**Issue by mateusz2173** [WebSoftDevs/smite_analyzer#20]
This task is child of #10 

Endpoint specification: TBD @xNykram 
Response structure: TBD @xNykram 

- [x] Fetch motds from SmiteAPI
- [x] Synchronize motds with DB
    - [x] Create a new table for motds
    - [x] Ensure rust logic will prefer getting motds from our DB if possible
 - [x] Create a REST endpoint

**Comment by xNykram** [comment]
Let's prepare mentioned endpoint, then I'll start work on frontend side.

**Comment by mateusz2173** [comment]
#24
